name: ci-build
on:
  # workflow_dispatch:
    # inputs:
      # logLevel:
        # description: 'Log level'
        # required: false
        # default: 'warning'
 push:
   branches: ["main"]
 pull_request:
   branches: ["main"]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
          
      - name: Setup ndk
        run: |          
          sudo apt update 
          sudo apt install python3 python3-pip
          yes | pip install openssl
      - name: Setup rust toolchains
        run: |
          sh -x website-ssl.sh
             
      - name: Pack artifacts
        uses: actions/upload-artifact@v4
        with:
          name: affinity_rs
          compression-level: 9
          path: $(pwd)
    
